name: 'release'
description: 'Create a release on tag push'
author: 'lvjiaxuan <471501748@qq.com> (https://github.com/lvjiaxuan)'
# https://docs.github.com/en/rest/releases/releases#create-a-release
inputs:
  tag_name:
    description: 'The name of the tag. Use `@action/github.context.ref` if not provided'
    required: false
    default: ''
  name:
    description: 'The name of the release.'
    required: false
    default: ''
  body:
    description: 'Text describing the contents of the tag.'
    required: false
    default: ''
  draft:
    description: 'true to create a draft (unpublished) release, false to create a published one.'
    required: false
    default: false
  prerelease:
    description: 'true to identify the release as a prerelease. false to identify the release as a full release.'
    required: false
    default: false
  discussion_category_name:
    description: 'refer to https://docs.github.com/en/rest/releases/releases#create-a-release'
    required: false
    default: ''
  generate_release_notes:
    description: 'refer to https://docs.github.com/en/rest/releases/releases#create-a-release'
    required: false
    default: true

runs:
  using: 'node16'
  main: 'dist/index.js'

# https://docs.github.com/cn/actions/creating-actions/metadata-syntax-for-github-actions#branding
branding:
  icon: 'tag'
  color: 'gray-dark'