name: 'Create a release'

on:
  push:
    tags:
      - 'v*'

jobs:
  release: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/pnpm/action-setup
      # - uses: pnpm/action-setup@master
      #   with:
      #     version: 7
      #     run_install: true

      - uses: ./
